package com.portfolio.features.resume.service;

import com.portfolio.features.education.entity.Education; import com.portfolio.features.education.repository.EducationRepository; import com.portfolio.features.experience.entity.Experience; import com.portfolio.features.experience.repository.ExperienceRepository; import com.portfolio.features.portfolio.entity.Portfolio; import com.portfolio.features.portfolio.repository.PortfolioRepository; import com.portfolio.features.portfolio.service.PortfolioAccessService; import com.portfolio.features.project.entity.*; import com.portfolio.features.project.repository.ProjectRepository; import com.portfolio.features.resume.dto.request.*; import com.portfolio.features.resume.dto.response.ResumeImportResponse; import com.portfolio.features.skill.entity.Skill; import com.portfolio.features.skill.repository.SkillRepository; import com.portfolio.features.user.entity.AppUser; import java.util.*; import lombok.RequiredArgsConstructor; import org.springframework.stereotype.Service;

@Service @RequiredArgsConstructor public class ResumeImportService {
  private final PortfolioAccessService access; private final PortfolioRepository portfolios; private final ExperienceRepository experiences; private final EducationRepository educations; private final SkillRepository skills; private final ProjectRepository projects;
  public ResumeImportResponse importResume(AppUser user, ResumeImportRequest request) {
    Portfolio portfolio=access.mine(user); boolean profileUpdated=profile(portfolio,request.profile()); if(profileUpdated) portfolios.save(portfolio);
    Counter experience=experiences(portfolio, request.experiences()); Counter education=educations(portfolio,request.educations()); Counter skill=skills(portfolio,request.skills()); Counter project=projects(portfolio,request.projects());
    return new ResumeImportResponse(experience.imported+education.imported+skill.imported+project.imported,experience.skipped+education.skipped+skill.skipped+project.skipped,experience.failed+education.failed+skill.failed+project.failed,profileUpdated,experience.result(),education.result(),skill.result(),project.result());
  }
  private boolean profile(Portfolio p, ResumeProfileImportRequest r){if(r==null||!r.selected())return false; boolean changed=false; if(text(r.fullName())){p.setFullName(r.fullName().trim());changed=true;} if(text(r.headline())){p.setHeadline(r.headline().trim());changed=true;} if(text(r.email())){p.setPublicEmail(r.email().trim());changed=true;} if(text(r.phone())){p.setPhone(r.phone().trim());changed=true;} if(text(r.location())){p.setLocation(r.location().trim());changed=true;} return changed;}
  private Counter experiences(Portfolio p,List<ResumeExperienceImportRequest> items){Counter c=new Counter(); List<Experience> existing=experiences.findByPortfolioIdOrderBySortOrderAscStartDateDesc(p.getId()); for(var r:list(items)){if(!r.selected())continue;try{if(!text(r.company())||!text(r.position())){c.failed++;continue;} if(existing.stream().anyMatch(e->same(e.getCompany(),r.company())&&same(e.getPosition(),r.position())&&Objects.equals(e.getStartDate(),r.startDate())&&Objects.equals(e.getEndDate(),r.endDate()))){c.skipped++;continue;} Experience e=new Experience();e.setPortfolio(p);e.setCompany(r.company().trim());e.setPosition(r.position().trim());e.setLocation(blank(r.location()));e.setStartDate(r.startDate());e.setEndDate(r.currentlyWorking()?null:r.endDate());e.setCurrentlyWorking(r.currentlyWorking());e.setDescription(blank(r.description()));e.setSortOrder(existing.size());experiences.save(e);existing.add(e);c.imported++;}catch(RuntimeException x){c.failed++;}}return c;}
  private Counter educations(Portfolio p,List<ResumeEducationImportRequest> items){Counter c=new Counter(); List<Education> existing=educations.findByPortfolioIdOrderBySortOrderAscStartDateDesc(p.getId()); for(var r:list(items)){if(!r.selected())continue;try{if(!text(r.school())){c.failed++;continue;} if(existing.stream().anyMatch(e->same(e.getSchool(),r.school())&&same(e.getDegree(),r.degree())&&Objects.equals(e.getStartDate(),r.startDate())&&Objects.equals(e.getEndDate(),r.endDate()))){c.skipped++;continue;} Education e=new Education();e.setPortfolio(p);e.setSchool(r.school().trim());e.setDegree(blank(r.degree()));e.setMajor(blank(r.major()));e.setStartDate(r.startDate());e.setEndDate(r.endDate());e.setDescription(blank(r.description()));e.setSortOrder(existing.size());educations.save(e);existing.add(e);c.imported++;}catch(RuntimeException x){c.failed++;}}return c;}
  private Counter skills(Portfolio p,List<ResumeSkillImportRequest> items){Counter c=new Counter();Set<String> known=new HashSet<>();skills.findByPortfolioIdOrderBySortOrderAscNameAsc(p.getId()).forEach(s->known.add(normalize(s.getName())));for(var r:list(items)){if(!r.selected())continue;try{if(!text(r.name())){c.failed++;continue;}if(!known.add(normalize(r.name()))){c.skipped++;continue;}Skill s=new Skill();s.setPortfolio(p);s.setName(r.name().trim());s.setCategory(blank(r.category()));s.setSortOrder(known.size()-1);skills.save(s);c.imported++;}catch(RuntimeException x){c.failed++;}}return c;}
  private Counter projects(Portfolio p,List<ResumeProjectImportRequest> items){Counter c=new Counter();List<Project> existing=projects.findByPortfolioIdOrderBySortOrderAscTitleAsc(p.getId());for(var r:list(items)){if(!r.selected())continue;try{if(!text(r.title())){c.failed++;continue;}if(existing.stream().anyMatch(e->same(e.getTitle(),r.title())||(text(r.githubUrl())&&same(e.getGithubUrl(),r.githubUrl())))){c.skipped++;continue;}Project project=new Project();project.setPortfolio(p);project.setTitle(r.title().trim());project.setSlug(slug(r.title()));project.setDescription(blank(r.description()));project.setGithubUrl(blank(r.githubUrl()));project.setDemoUrl(blank(r.demoUrl()));project.setSource("RESUME");project.setFeatured(false);project.setSortOrder(existing.size());Set<String> tech=new LinkedHashSet<>();for(String value:list(r.technologies()))if(text(value))tech.add(value.trim());int order=0;for(String value:tech){ProjectTechnology pt=new ProjectTechnology();pt.setProject(project);pt.setTechnology(value);pt.setSortOrder(order++);project.getTechnologies().add(pt);}projects.save(project);existing.add(project);c.imported++;}catch(RuntimeException x){c.failed++;}}return c;}
  private static boolean text(String value){return value!=null&&!value.isBlank();} private static String blank(String value){return text(value)?value.trim():null;} private static boolean same(String a,String b){return normalize(a).equals(normalize(b));} private static String normalize(String value){return value==null?"":value.trim().toLowerCase(Locale.ROOT);} private static String slug(String value){return value.toLowerCase(Locale.ROOT).trim().replaceAll("[^a-z0-9]+","-").replaceAll("(^-|-$)","");} private static <T> List<T> list(List<T> value){return value==null?List.of():value;} private static class Counter{int imported,skipped,failed;ResumeImportResponse.Section result(){return new ResumeImportResponse.Section(imported,skipped,failed);}}
}
