"use client";
import { ArrowDown, ArrowUp, GripVertical } from "lucide-react";
import { getTemplateById, type PortfolioSection, type TemplateId } from "@/components/portfolio/templates";
import { Button } from "@/components/ui";
export function SectionsPanel({ sections, templateId, busy, onSave }: { sections: PortfolioSection[]; templateId: TemplateId; busy: boolean; onSave: (sections: PortfolioSection[]) => void | Promise<void> }) {
  const template = getTemplateById(templateId);
  const update = (sectionType: PortfolioSection["sectionType"], change: Partial<PortfolioSection>) => onSave(sections.map((item) => item.sectionType === sectionType ? { ...item, ...change } : item));
  const move = (index: number, direction: -1 | 1) => { const target = index + direction; if (target < 0 || target >= sections.length) return; const next = [...sections]; [next[index], next[target]] = [next[target], next[index]]; void onSave(next); };
  return <div className="space-y-2">{sections.map((item, index) => { const layouts = template.supportedSectionLayouts[item.sectionType] ?? []; return <div key={item.sectionType} className="rounded-lg border p-3"><div className="flex items-center gap-2"><GripVertical aria-hidden="true" size={16} className="text-muted"/><input aria-label={`Show ${item.sectionType}`} aria-describedby={item.sectionType === "HERO" ? "hero-required" : undefined} type="checkbox" checked={item.enabled} disabled={item.sectionType === "HERO" || busy} onChange={(event) => void update(item.sectionType, { enabled: event.target.checked })}/><span className="flex-1 text-sm font-medium">{item.sectionType[0] + item.sectionType.slice(1).toLowerCase()}{item.sectionType === "HERO" && <span id="hero-required" className="ml-1 font-normal text-muted">(required)</span>}</span><Button aria-label={`Move ${item.sectionType} up`} type="button" className="bg-transparent p-1 text-muted" disabled={index === 0 || busy} onClick={() => move(index, -1)}><ArrowUp size={15}/></Button><Button aria-label={`Move ${item.sectionType} down`} type="button" className="bg-transparent p-1 text-muted" disabled={index === sections.length - 1 || busy} onClick={() => move(index, 1)}><ArrowDown size={15}/></Button></div>{layouts.length > 0 && <label className="mt-2 block text-xs text-muted">Layout<select aria-label={`${item.sectionType} layout`} value={item.layout ?? layouts[0]} disabled={busy} onChange={(event) => void update(item.sectionType, { layout: event.target.value })} className="mt-1 w-full rounded border bg-white p-1.5 text-sm text-ink">{layouts.map((layout) => <option key={layout} value={layout}>{layout[0].toUpperCase() + layout.slice(1)}</option>)}</select></label>}</div>; })}</div>;
}
