package com.portfolio.features.ai.provider;
import com.fasterxml.jackson.databind.ObjectMapper; import com.portfolio.features.ai.config.AiConfiguration; import java.net.URI; import java.net.http.*; import java.nio.charset.StandardCharsets; import java.time.Duration; import java.util.List; import java.util.Map; import org.springframework.boot.autoconfigure.condition.ConditionalOnProperty; import org.springframework.stereotype.Component;
@Component @ConditionalOnProperty(name="ai.provider",havingValue="gemini")
public class GeminiProvider implements AiProvider {
 private final AiConfiguration config; private final ObjectMapper json; private final HttpClient client;
 public GeminiProvider(AiConfiguration config,ObjectMapper json){this.config=config;this.json=json;this.client=HttpClient.newBuilder().connectTimeout(Duration.ofSeconds(config.getTimeoutSeconds())).build();}
 @Override public String generate(String instructions,String text){if(!config.available())throw new AiWritingException("AI is not configured. Set AI_PROVIDER, AI_API_KEY, and AI_MODEL, then restart the backend.");try{URI endpoint=URI.create("https://generativelanguage.googleapis.com/v1beta/models/"+config.getModel()+":generateContent");var body=json.writeValueAsString(Map.of("system_instruction",Map.of("parts",List.of(Map.of("text",instructions))),"contents",List.of(Map.of("role","user","parts",List.of(Map.of("text",text)))),"generationConfig",Map.of("maxOutputTokens",2200)));var request=HttpRequest.newBuilder(endpoint).timeout(Duration.ofSeconds(config.getTimeoutSeconds())).header("x-goog-api-key",config.getApiKey()).header("Content-Type","application/json").POST(HttpRequest.BodyPublishers.ofString(body,StandardCharsets.UTF_8)).build();var response=client.send(request,HttpResponse.BodyHandlers.ofString(StandardCharsets.UTF_8));if(response.statusCode()!=200||response.body().length()>100000)throw unavailable(response.statusCode());String output=json.readTree(response.body()).path("candidates").path(0).path("content").path("parts").path(0).path("text").asText();if(output.isBlank())throw new AiWritingException("Gemini did not return a usable suggestion. Please try again.");return output;}catch(HttpTimeoutException e){throw new AiWritingException(true);}catch(InterruptedException e){Thread.currentThread().interrupt();throw new AiWritingException(false);}catch(AiWritingException e){throw e;}catch(Exception e){throw new AiWritingException("Gemini request failed. Please try again.");}}
 private AiWritingException unavailable(int status){return switch(status){case 400,404->new AiWritingException("Gemini rejected the configured model. Check AI_MODEL.");case 401,403->new AiWritingException("Gemini rejected the configured API key.");case 429->new AiWritingException("Gemini rate limit or quota reached. Check the Google AI project usage.");default->new AiWritingException("Gemini service returned HTTP "+status+". Please try again shortly.");};}
}
