import { CreativeTemplate } from "./creative/creative-template";
import { DeveloperTemplate } from "./developer/developer-template";
import { MinimalTemplate } from "./minimal/minimal-template";
import { ModernTemplate } from "./modern/modern-template";
import { ProfessionalTemplate } from "./professional/professional-template";
import { StudentTemplate } from "./student/student-template";
import type { PortfolioTemplateDefinition, PortfolioTheme, TemplateId } from "./types";

const base: PortfolioTheme = { mode: "light", primaryColor: "#20419E", backgroundColor: "#FFFFFF", surfaceColor: "#F4F6FA", textColor: "#111827", mutedTextColor: "#667085", fontHeading: "geist", fontBody: "inter", borderRadius: "medium", contentWidth: "medium", spacing: "normal" };
const standard = ["HERO", "ABOUT", "EXPERIENCE", "PROJECTS", "SKILLS", "EDUCATION", "SOCIAL", "RESUME"] as const;
const layouts = { HERO: ["minimal", "centered", "split"], PROJECTS: ["grid", "list", "featured"], EXPERIENCE: ["timeline", "cards", "list"], SKILLS: ["tags", "grid", "grouped"] };
export const PORTFOLIO_TEMPLATES: PortfolioTemplateDefinition[] = [
  { id: "minimal", name: "Minimal", description: "Typography-first, quiet, and exceptionally easy to scan.", category: "MINIMAL", recommendedFor: ["Engineers", "Consultants", "General professionals"], tier: "FREE", thumbnail: "/templates/minimal.svg", supportsDarkMode: true, defaultTheme: { ...base, borderRadius: "small", contentWidth: "narrow", spacing: "relaxed" }, defaultSectionOrder: [...standard], supportedSectionLayouts: { ...layouts, PROJECTS: ["list", "grid"] }, component: MinimalTemplate },
  { id: "developer", name: "Developer", description: "Technical, project-led, and built to make skills and source links clear.", category: "DEVELOPER", recommendedFor: ["Software developers", "DevOps", "Engineers"], tier: "FREE", thumbnail: "/templates/developer.svg", supportsDarkMode: true, defaultTheme: { ...base, mode: "dark", primaryColor: "#4ADE80", backgroundColor: "#0B1220", surfaceColor: "#111C2F", textColor: "#F8FAFC", mutedTextColor: "#94A3B8", fontHeading: "geist-mono", contentWidth: "wide" }, defaultSectionOrder: ["HERO", "PROJECTS", "SKILLS", "EXPERIENCE", "EDUCATION", "ABOUT", "SOCIAL", "RESUME"], supportedSectionLayouts: { ...layouts, PROJECTS: ["grid", "featured"] }, component: DeveloperTemplate },
  { id: "modern", name: "Modern", description: "A bold introduction, crisp cards, and polished contemporary spacing.", category: "PROFESSIONAL", recommendedFor: ["Product people", "Startup teams", "Engineers"], tier: "FREE", thumbnail: "/templates/modern.svg", supportsDarkMode: true, defaultTheme: { ...base, primaryColor: "#4F46E5", fontHeading: "manrope", borderRadius: "large", contentWidth: "wide" }, defaultSectionOrder: [...standard], supportedSectionLayouts: layouts, component: ModernTemplate },
  { id: "professional", name: "Professional", description: "Formal and experience-focused for a confident business presence.", category: "PROFESSIONAL", recommendedFor: ["Consultants", "Managers", "Finance professionals"], tier: "FREE", thumbnail: "/templates/professional.svg", supportsDarkMode: true, defaultTheme: { ...base, primaryColor: "#1E3A5F", surfaceColor: "#F3F4F6", fontHeading: "source-sans", borderRadius: "none", spacing: "compact" }, defaultSectionOrder: ["HERO", "ABOUT", "EXPERIENCE", "EDUCATION", "SKILLS", "PROJECTS", "SOCIAL", "RESUME"], supportedSectionLayouts: { ...layouts, EXPERIENCE: ["timeline", "list"] }, component: ProfessionalTemplate },
  { id: "creative", name: "Creative", description: "An editorial, image-led canvas that keeps navigation and reading effortless.", category: "CREATIVE", recommendedFor: ["Designers", "Photographers", "Creative developers"], tier: "PRO", thumbnail: "/templates/creative.svg", supportsDarkMode: true, defaultTheme: { ...base, primaryColor: "#DB2777", surfaceColor: "#FFF1F5", fontHeading: "playfair", borderRadius: "large", contentWidth: "wide", spacing: "relaxed" }, defaultSectionOrder: ["HERO", "PROJECTS", "ABOUT", "SKILLS", "EXPERIENCE", "EDUCATION", "SOCIAL", "RESUME"], supportedSectionLayouts: { ...layouts, PROJECTS: ["featured", "grid"] }, component: CreativeTemplate },
  { id: "student", name: "Student", description: "Education, skills, projects, and resume calls-to-action take priority.", category: "STUDENT", recommendedFor: ["Students", "Graduates", "Internship applicants"], tier: "FREE", thumbnail: "/templates/student.svg", supportsDarkMode: true, defaultTheme: { ...base, primaryColor: "#7C3AED", surfaceColor: "#F5F3FF", fontHeading: "manrope" }, defaultSectionOrder: ["HERO", "EDUCATION", "PROJECTS", "SKILLS", "RESUME", "EXPERIENCE", "ABOUT", "SOCIAL"], supportedSectionLayouts: layouts, component: StudentTemplate },
];
export const portfolioTemplateList = PORTFOLIO_TEMPLATES;
export const portfolioTemplateRegistry = Object.fromEntries(PORTFOLIO_TEMPLATES.map((template) => [template.id, template])) as Record<TemplateId, PortfolioTemplateDefinition>;
export function getTemplateById(id?: string) { return portfolioTemplateRegistry[id as TemplateId] ?? portfolioTemplateRegistry.modern; }
export function isTemplateId(id: string): id is TemplateId { return id in portfolioTemplateRegistry; }
