"use client";
import { useEffect, useState } from "react";
import { Github } from "lucide-react";
import { githubApi, type Repo } from "@/features/github/api";

export function GitHubImportPanel() {
  const [status, setStatus] = useState<Awaited<ReturnType<typeof githubApi.status>> | null>(null);
  const [repos, setRepos] = useState<Repo[]>([]); const [page, setPage] = useState(1); const [more, setMore] = useState(false); const [selected, setSelected] = useState(new Set<number>()); const [query, setQuery] = useState(""); const [filter, setFilter] = useState("all"); const [busy, setBusy] = useState(false); const [message, setMessage] = useState("");
  const load = async (next = 1, append = false) => { setBusy(true); try { const result = await githubApi.repositories(next); setRepos((old) => append ? [...old, ...result.items.filter((item) => !old.some((existing) => existing.githubId === item.githubId))] : result.items); setPage(next); setMore(result.hasMore); } catch (error) { setMessage(error instanceof Error ? error.message : "Unable to load repositories."); } finally { setBusy(false); } };
  useEffect(() => { githubApi.status().then((value) => { setStatus(value); if (value.connected) void load(); }).catch(() => setMessage("Unable to load GitHub connection.")); }, []);
  if (!status) return <section className="rounded-xl border bg-white p-6">Checking GitHub connection...</section>;
  if (!status.connected) return <section className="rounded-xl border bg-white p-6"><Github className="text-primary" /><h2 className="mt-3 text-xl font-bold">Import projects from GitHub</h2><p className="mt-2 text-muted">Connect your GitHub account and import repositories directly into your portfolio.</p><button disabled={busy} onClick={async () => { setBusy(true); try { window.location.assign((await githubApi.connect()).authorizationUrl); } catch { setMessage("Unable to connect GitHub."); setBusy(false); } }} className="mt-5 rounded bg-primary px-4 py-2 text-white">{busy ? "Connecting..." : "Connect GitHub"}</button>{message && <p className="mt-3 text-sm text-red-600">{message}</p>}</section>;
  const shown = repos.filter((repo) => (filter === "all" || filter === "forks" ? repo.fork : !repo.fork) && `${repo.name} ${repo.fullName} ${repo.description ?? ""}`.toLowerCase().includes(query.toLowerCase()));
  const toggle = (id: number) => setSelected((value) => { const next = new Set(value); if (next.has(id)) { next.delete(id); } else { next.add(id); } return next; });
  return <section className="rounded-xl border bg-white p-6"><div className="flex items-center justify-between gap-3"><div className="flex items-center gap-3"><Github /><div><h2 className="font-bold">Connected to GitHub</h2><p className="text-sm text-muted">@{status.username}</p></div></div><button onClick={() => { if (window.confirm("Disconnect GitHub? Imported projects will remain.")) void githubApi.disconnect().then(() => { setStatus({ connected: false }); setRepos([]); setSelected(new Set()); }); }} className="rounded border px-3 py-2 text-sm">Disconnect</button></div><input aria-label="Search repositories" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search repositories..." className="mt-6 w-full rounded border px-3 py-2" /><div className="mt-3 flex gap-2">{["all", "original", "forks"].map((item) => <button key={item} onClick={() => setFilter(item)} className="rounded bg-surface px-3 py-1 text-sm">{item}</button>)}</div><div className="mt-5 space-y-3">{shown.map((repo) => { const disabled = repo.alreadyImported || repo.privateRepository || repo.archived; return <label key={repo.githubId} className={`block rounded border p-4 ${disabled ? "opacity-60" : ""}`}><input aria-label={`Select ${repo.name}`} type="checkbox" disabled={disabled || busy} checked={selected.has(repo.githubId)} onChange={() => toggle(repo.githubId)} /><a className="ml-3 font-semibold text-primary" href={repo.repositoryUrl} target="_blank" rel="noopener noreferrer">{repo.name}</a><p className="ml-7 text-sm text-muted">{repo.description || "No description."}</p><p className="ml-7 text-xs">{repo.primaryLanguage} ★ {repo.stars} {repo.alreadyImported ? "Imported" : repo.privateRepository ? "Private" : repo.archived ? "Archived" : repo.fork ? "Fork" : ""}</p></label>; })}</div><div className="mt-6 flex flex-wrap gap-3"><button disabled={!selected.size || busy} onClick={() => void (async () => { setBusy(true); try { const result = await githubApi.import([...selected]); setMessage(`${result.imported} projects imported. ${result.skipped} skipped. ${result.failed} failed.`); setSelected(new Set()); await load(); } catch { setMessage("Unable to import selected repositories."); } finally { setBusy(false); } })()} className="rounded bg-primary px-4 py-2 text-white">{busy ? "Importing projects..." : `Import ${selected.size} Projects`}</button>{more && <button disabled={busy} onClick={() => void load(page + 1, true)} className="rounded border px-4 py-2">Load More</button>}<span>{selected.size} selected</span></div>{message && <p className="mt-4 text-sm text-primary">{message}</p>}</section>;
}
