"use client";
import { useState } from "react";
import { useParseResumeMutation, type ResumePreview } from "@/features/resume/rtk-api";

export function ResumeImportPanel({ hasResume, onGoToResume }: { hasResume: boolean; onGoToResume: () => void }) {
  const [preview, setPreview] = useState<ResumePreview | null>(null); const [parseResume, { isLoading, isError, error }] = useParseResumeMutation();
  const analyze = async () => { try { setPreview((await parseResume().unwrap()).data); } catch { /* RTK Query state supplies the safe error message. */ } };
  if (!hasResume) return <section className="rounded-xl border bg-white p-6"><h2 className="text-xl font-bold">Resume Import</h2><p className="mt-2 text-muted">Upload a resume before analyzing it.</p><button onClick={onGoToResume} className="mt-5 rounded bg-primary px-4 py-2 text-white">Go to Resume</button></section>;
  if (!preview) return <section className="rounded-xl border bg-white p-6"><h2 className="text-xl font-bold">Resume Import</h2><p className="mt-2 text-muted">Turn your uploaded resume into structured portfolio information.</p><button disabled={isLoading} onClick={() => void analyze()} className="mt-5 rounded bg-primary px-4 py-2 text-white">{isLoading ? "Analyzing resume…" : "Analyze Resume"}</button>{isError && <p className="mt-4 text-sm text-red-600">{error && "message" in error ? error.message : "Unable to analyze resume."}</p>}</section>;
  return <section className="rounded-xl border bg-white p-6"><h2 className="text-xl font-bold">Resume analyzed</h2><p className="mt-2 text-muted">Review the detected information. Nothing has been imported.</p><div className="mt-6 grid grid-cols-2 gap-3 text-sm"><Stat label="Experience" value={preview.experiences.length} /><Stat label="Education" value={preview.educations.length} /><Stat label="Skills" value={preview.skills.length} /><Stat label="Projects" value={preview.projects.length} /></div>{preview.profile.fullName && <Preview title="Profile"><p className="font-semibold">{preview.profile.fullName}</p><p>{preview.profile.headline}</p><p>{preview.profile.email}</p></Preview>}{preview.experiences.length > 0 && <Preview title="Experience">{preview.experiences.map((item, index) => <div key={index} className="mb-3"><p className="font-semibold">{item.position}</p><p>{item.company} {item.startDate && `· ${item.startDate}${item.currentlyWorking ? " – Present" : item.endDate ? ` – ${item.endDate}` : ""}`}</p><p className="text-muted">{item.description}</p></div>)}</Preview>}{preview.educations.length > 0 && <Preview title="Education">{preview.educations.map((item, index) => <div key={index} className="mb-3"><p className="font-semibold">{item.degree}</p><p>{item.school}</p><p className="text-muted">{item.major}</p></div>)}</Preview>}{preview.skills.length > 0 && <Preview title="Skills"><div className="flex flex-wrap gap-2">{preview.skills.map((skill) => <span key={skill.name} className="rounded-full bg-surface px-3 py-1 text-sm">{skill.name}</span>)}</div></Preview>}{preview.projects.length > 0 && <Preview title="Projects">{preview.projects.map((project, index) => <p key={index}>{project.title}</p>)}</Preview>}{preview.warnings.length > 0 && <div className="mt-6 rounded-lg bg-amber-50 p-4 text-sm text-amber-900"><p className="font-semibold">Review notes</p><ul className="mt-2 list-disc pl-5">{preview.warnings.map((warning) => <li key={warning}>{warning}</li>)}</ul></div>}</section>;
}
function Stat({ label, value }: { label: string; value: number }) { return <div className="rounded-lg bg-surface p-3"><p className="text-muted">{label}</p><p className="text-2xl font-bold">{value}</p></div>; }
function Preview({ title, children }: { title: string; children: React.ReactNode }) { return <div className="mt-6"><h3 className="font-semibold">{title}</h3><div className="mt-2 text-sm">{children}</div></div>; }
