"use client";

import { useState } from "react";
import { zodResolver } from "@hookform/resolvers/zod";
import { type Path, type UseFormReturn, useFieldArray, useForm, useWatch } from "react-hook-form";
import { Alert, AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle, Badge, Button, Card, Checkbox, Form, Input, Separator, Textarea } from "@/components/ui";
import { useImportResumeMutation, useParseResumeMutation, type ResumeImportResponse, type ResumePreview } from "@/features/resume/rtk-api";
import { mapFormValuesToImportRequest, mapResumePreviewToFormValues, resumeImportSchema, type ResumeImportFormValues } from "@/features/resume/schema";

type Props = { hasResume: boolean; onGoToResume: () => void };
type Section = "experiences" | "educations" | "skills" | "projects";
const defaults: ResumeImportFormValues = { profile: { selected: false, fullName: "", headline: "", email: "", phone: "", location: "", website: "", linkedinUrl: "", githubUrl: "" }, experiences: [], educations: [], skills: [], projects: [] };

export function ResumeImportPanel({ hasResume, onGoToResume }: Props) {
  const form = useForm<ResumeImportFormValues>({ resolver: zodResolver(resumeImportSchema), defaultValues: defaults });
  const [parseResume, parse] = useParseResumeMutation(); const [importResume, imported] = useImportResumeMutation();
  const [preview, setPreview] = useState<ResumePreview | null>(null); const [confirming, setConfirming] = useState(false); const [result, setResult] = useState<ResumeImportResponse | null>(null);
  useFieldArray({ control: form.control, name: "experiences" }); useFieldArray({ control: form.control, name: "educations" }); useFieldArray({ control: form.control, name: "skills" }); useFieldArray({ control: form.control, name: "projects" });
  const watched = useWatch({ control: form.control });
  const values = { ...defaults, ...watched, profile: { ...defaults.profile, ...watched.profile }, experiences: watched.experiences ?? [], educations: watched.educations ?? [], skills: watched.skills ?? [], projects: watched.projects ?? [] };
  const analyze = async () => { try { const parsed = (await parseResume().unwrap()).data; form.reset(mapResumePreviewToFormValues(parsed)); setPreview(parsed); setResult(null); } catch { /* RTK Query error state is rendered below. */ } };
  const submit = async () => { try { const response = await importResume(mapFormValuesToImportRequest(form.getValues())).unwrap(); setResult(response.data); setConfirming(false); } catch { setConfirming(false); } };
  if (!hasResume) return <Card className="p-6"><h2 className="text-xl font-bold">Resume Import</h2><p className="mt-2 text-muted">Upload a resume before analyzing it.</p><Button className="mt-5" onClick={onGoToResume}>Go to Resume</Button></Card>;
  if (!preview) return <Card className="p-6"><h2 className="text-xl font-bold">Resume Import</h2><p className="mt-2 text-muted">Turn your uploaded resume into structured portfolio information.</p><Button className="mt-5" disabled={parse.isLoading} onClick={() => void analyze()}>{parse.isLoading ? "Analyzing resume…" : "Analyze Resume"}</Button>{parse.isError && <Alert className="mt-4 border-red-200 text-red-700">{errorMessage(parse.error, "Unable to analyze resume.")}</Alert>}</Card>;
  return <Form {...form}><form onSubmit={form.handleSubmit(() => setConfirming(true))} className="space-y-6"><Card className="p-6"><h2 className="text-xl font-bold">Review resume import</h2><p className="mt-2 text-muted">Edit detected values and select only the records to import.</p>{preview.warnings.length ? <Alert className="mt-4 border-amber-200 bg-amber-50"><strong>Review notes</strong><ul className="mt-2 list-disc pl-5">{preview.warnings.map((warning) => <li key={warning}>{warning}</li>)}</ul></Alert> : null}</Card><Profile form={form} /><Records form={form} title="Experience" name="experiences" fields={["position", "company", "location", "startDate", "endDate", "description"]} values={values.experiences} /><Records form={form} title="Education" name="educations" fields={["school", "degree", "major", "startDate", "endDate", "description"]} values={values.educations} /><Records form={form} title="Skills" name="skills" fields={["name", "category"]} values={values.skills} /><Records form={form} title="Projects" name="projects" fields={["title", "description", "githubUrl", "demoUrl", "technologies"]} values={values.projects} />{imported.isError && <Alert className="border-red-200 text-red-700">{errorMessage(imported.error, "Import failed. Your selections and edits were preserved; please try again.")}</Alert>}{result && <ImportResult result={result} />}<Button type="submit" disabled={imported.isLoading}>{imported.isLoading ? "Importing…" : "Import Selected"}</Button><AlertDialog open={confirming} onOpenChange={setConfirming}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Import selected resume data?</AlertDialogTitle><AlertDialogDescription>Profile selected: {values.profile.selected ? "yes" : "no"}. Experiences: {selected(values.experiences)}. Education: {selected(values.educations)}. Skills: {selected(values.skills)}. Projects: {selected(values.projects)}.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Cancel</AlertDialogCancel><AlertDialogAction><span onClick={() => void submit()}>Confirm import</span></AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog></form></Form>;
}

function Profile({ form }: { form: UseFormReturn<ResumeImportFormValues> }) { return <Card className="p-5"><label className="flex items-center gap-2 font-semibold"><Checkbox {...form.register("profile.selected")} /> Profile</label><div className="mt-4 grid gap-3 md:grid-cols-2">{(["fullName", "headline", "email", "phone", "location", "website", "linkedinUrl", "githubUrl"] as const).map((field) => <Field key={field} form={form} path={`profile.${field}`} label={human(field)} />)}</div></Card>; }
function Records({ form, title, name, fields, values }: { form: UseFormReturn<ResumeImportFormValues>; title: string; name: Section; fields: string[]; values: Array<{ selected?: boolean }> }) { const setAll = (state: boolean) => values.forEach((_, index) => form.setValue(`${name}.${index}.selected` as Path<ResumeImportFormValues>, state)); return <Card className="p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><h3 className="font-semibold">{title}</h3><Badge>{selected(values)} selected</Badge></div><div className="flex gap-2"><Button type="button" onClick={() => setAll(true)} disabled={!values.length}>Select all</Button><Button type="button" onClick={() => setAll(false)} disabled={!values.length}>Deselect all</Button></div></div>{values.length === 0 ? <p className="mt-3 text-sm text-muted">No {title.toLowerCase()} detected.</p> : <div className="mt-4 space-y-3">{values.map((_, index) => <div className="rounded border p-4" key={index}><label className="flex items-center gap-2 text-sm font-medium"><Checkbox {...form.register(`${name}.${index}.selected` as Path<ResumeImportFormValues>)} /> Import this record</label><Separator /><div className="grid gap-3 md:grid-cols-2">{fields.map((field) => <Field key={field} form={form} path={`${name}.${index}.${field}` as Path<ResumeImportFormValues>} label={field === "technologies" ? "Technologies (comma-separated)" : human(field)} textarea={field === "description"} type={field.includes("Date") ? "date" : "text"} technologies={field === "technologies"} />)}</div>{name === "experiences" && <label className="mt-3 flex items-center gap-2 text-sm"><Checkbox {...form.register(`${name}.${index}.currentlyWorking` as Path<ResumeImportFormValues>)} /> Currently working</label>}</div>)}</div>}</Card>; }
function Field({ form, path, label, textarea = false, type = "text", technologies = false }: { form: UseFormReturn<ResumeImportFormValues>; path: Path<ResumeImportFormValues>; label: string; textarea?: boolean; type?: string; technologies?: boolean }) { const registration = form.register(path, technologies ? { setValueAs: (value: string) => value.split(",").map((item) => item.trim()).filter(Boolean) } : undefined); const technologyValue = technologies ? (form.watch(path) as string[]).join(", ") : undefined; const error = fieldError(form.formState.errors, path); return <label className="grid gap-1 text-sm"><span>{label}</span>{textarea ? <Textarea {...registration} aria-invalid={Boolean(error)} /> : <Input {...registration} type={type} value={technologyValue} aria-invalid={Boolean(error)} />}{error ? <span className="text-sm text-red-700" role="alert">{error}</span> : null}</label>; }
function ImportResult({ result }: { result: ResumeImportResponse }) { return <Alert className="border-green-200 bg-green-50"><strong>Import complete.</strong> Imported: {result.imported}; already exists: {result.skipped}; failed: {result.failed}; profile updated: {result.profileUpdated ? "yes" : "no"}.{(["experiences", "educations", "skills", "projects"] as const).map((name) => <p key={name}>{human(name)} — imported {result[name].imported}, Already exists {result[name].skipped}, failed {result[name].failed}</p>)}</Alert>; }
function selected(values: Array<{ selected?: boolean }>) { return values.filter((value) => value.selected).length; } function fieldError(errors: unknown, path: string) { const error = path.split(".").reduce<unknown>((current, key) => typeof current === "object" && current !== null ? (current as Record<string, unknown>)[key] : undefined, errors); return typeof error === "object" && error !== null && "message" in error && typeof error.message === "string" ? error.message : undefined; } function human(value: string) { return value.replace(/([A-Z])/g, " $1").replace(/^./, (letter) => letter.toUpperCase()); } function errorMessage(error: unknown, fallback: string) { return typeof error === "object" && error !== null && "message" in error && typeof error.message === "string" ? error.message : fallback; }
