import { fireEvent, render, screen, waitFor } from "@testing-library/react";
import { beforeEach, describe, expect, it, vi } from "vitest";
import { ResumeImportPanel } from "./resume-import-panel";

const api = vi.hoisted(() => ({ parse: vi.fn(), import: vi.fn(), parseState: { isLoading: false, isError: false, error: undefined as unknown }, importState: { isLoading: false, isError: false, error: undefined as unknown } }));
vi.mock("@/features/resume/rtk-api", () => ({ useParseResumeMutation: () => [api.parse, api.parseState], useImportResumeMutation: () => [api.import, api.importState] }));
const preview = { profile: { fullName: "Ada Lovelace", email: "ada@example.com" }, experiences: [{ position: "Engineer", company: "Analytical Engines", currentlyWorking: false, rawText: "" }], educations: [], skills: [{ name: "Mathematics" }], projects: [], warnings: ["No projects section was detected."] };

describe("ResumeImportPanel", () => {
  beforeEach(() => { vi.resetAllMocks(); api.parseState.isError = false; api.importState.isError = false; });
  it("shows upload guidance when missing", () => { const go = vi.fn(); render(<ResumeImportPanel hasResume={false} onGoToResume={go} />); fireEvent.click(screen.getByRole("button", { name: "Go to Resume" })); expect(go).toHaveBeenCalled(); });
  it("maps real parse data into editable fields and selections", async () => { api.parse.mockReturnValue({ unwrap: vi.fn().mockResolvedValue({ data: preview }) }); render(<ResumeImportPanel hasResume onGoToResume={vi.fn()} />); fireEvent.click(screen.getByRole("button", { name: "Analyze Resume" })); expect(await screen.findByDisplayValue("Ada Lovelace")).toBeInTheDocument(); expect(screen.getByText("Review notes")).toBeInTheDocument(); expect(screen.getAllByText("1 selected")).toHaveLength(2); });
  it("selects and deselects a section", async () => { api.parse.mockReturnValue({ unwrap: vi.fn().mockResolvedValue({ data: preview }) }); render(<ResumeImportPanel hasResume onGoToResume={vi.fn()} />); fireEvent.click(screen.getByText("Analyze Resume")); await screen.findByDisplayValue("Engineer"); fireEvent.click(screen.getAllByText("Deselect all")[0]); expect(screen.getAllByText("0 selected")[0]).toBeInTheDocument(); fireEvent.click(screen.getAllByText("Select all")[0]); expect(screen.getAllByText("1 selected")[0]).toBeInTheDocument(); });
  it("shows selected-record validation while allowing incomplete unselected records", async () => { api.parse.mockReturnValue({ unwrap: vi.fn().mockResolvedValue({ data: preview }) }); render(<ResumeImportPanel hasResume onGoToResume={vi.fn()} />); fireEvent.click(screen.getByText("Analyze Resume")); const company = await screen.findByDisplayValue("Analytical Engines"); fireEvent.change(company, { target: { value: "" } }); fireEvent.click(screen.getByText("Import Selected")); expect(await screen.findByText("Company is required for selected experience.")).toBeInTheDocument(); expect(api.import).not.toHaveBeenCalled(); fireEvent.click(screen.getAllByLabelText("Import this record")[0]); fireEvent.click(screen.getByText("Import Selected")); expect(await screen.findByRole("dialog")).toBeInTheDocument(); });
  it("preserves edited values and selections when import fails", async () => { api.parse.mockReturnValue({ unwrap: vi.fn().mockResolvedValue({ data: preview }) }); api.import.mockReturnValue({ unwrap: vi.fn().mockRejectedValue(new Error("offline")) }); render(<ResumeImportPanel hasResume onGoToResume={vi.fn()} />); fireEvent.click(screen.getByText("Analyze Resume")); const company = await screen.findByDisplayValue("Analytical Engines"); fireEvent.change(company, { target: { value: "Edited Company" } }); fireEvent.click(screen.getAllByLabelText("Import this record")[0]); fireEvent.click(screen.getByText("Import Selected")); await screen.findByRole("dialog"); fireEvent.click(screen.getByText("Confirm import")); await waitFor(() => expect(api.import).toHaveBeenCalled()); expect(screen.getByDisplayValue("Edited Company")).toBeInTheDocument(); expect(screen.getAllByLabelText("Import this record")[0]).not.toBeChecked(); });
});
