spring:
  application:
    name: portfolio-builder-api
  profiles:
    default: dev
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true

server:
  port: ${SERVER_PORT:8081}
