"use client";
import { useMemo, useState } from "react";
import { Eye, Monitor, Smartphone, Tablet, X } from "lucide-react";
import { PortfolioRenderer } from "@/components/portfolio/renderer/portfolio-renderer";
import { portfolioTemplateList, type PortfolioRenderData, type TemplateCategory, type TemplateId } from "@/components/portfolio/templates";
import { Badge, Button, Card } from "@/components/ui";
const demo: PortfolioRenderData = { fullName: "Alex Morgan", headline: "Product designer building thoughtful digital experiences", bio: "I turn complex product problems into clear, useful experiences.", projects: [{ id: "demo-project", title: "Selected project", slug: "selected-project", shortDescription: "A focused case study showing process, decisions, and measurable results.", featured: true, sortOrder: 1, technologies: ["Research", "Design systems"] }], experiences: [], educations: [{ id: "demo-education", school: "Design Institute", degree: "Bachelor of Design", sortOrder: 1 }], skills: [{ id: "demo-skill-1", name: "Product design", sortOrder: 1 }, { id: "demo-skill-2", name: "Prototyping", sortOrder: 2 }], socialLinks: [] };
type Device = "desktop" | "tablet" | "mobile"; const widths: Record<Device, string> = { desktop: "100%", tablet: "768px", mobile: "390px" }; const categories: Array<"ALL" | TemplateCategory> = ["ALL", "PROFESSIONAL", "DEVELOPER", "CREATIVE", "STUDENT", "MINIMAL"];
export function PublicTemplateGallery() { const [category, setCategory] = useState<(typeof categories)[number]>("ALL"); const [preview, setPreview] = useState<TemplateId | null>(null); const [device, setDevice] = useState<Device>("desktop"); const shown = useMemo(() => category === "ALL" ? portfolioTemplateList : portfolioTemplateList.filter((item) => item.category === category), [category]); return <><div className="flex flex-wrap gap-2" aria-label="Template categories">{categories.map((item) => <Button key={item} type="button" onClick={() => setCategory(item)} className={category === item ? "" : "bg-white text-primary ring-1 ring-border"}>{item === "ALL" ? "All" : item[0] + item.slice(1).toLowerCase()}</Button>)}</div><div className="mt-8 grid gap-6 md:grid-cols-2 xl:grid-cols-3">{shown.map((template) => <Card key={template.id} className="overflow-hidden p-0"><div className="h-56 bg-surface p-5"><div className="h-full rounded-lg border bg-white p-5 shadow-sm"><div className="h-3 w-24 rounded" style={{ background: template.defaultTheme.primaryColor }} /><div className="mt-5 h-7 w-2/3 rounded bg-slate-800/80"/><div className="mt-3 h-2 w-full rounded bg-slate-200"/><div className="mt-8 grid grid-cols-2 gap-3"><div className="h-16 rounded border"/><div className="h-16 rounded border"/></div></div></div><div className="p-5"><div className="flex justify-between gap-3"><h2 className="text-xl font-bold">{template.name}</h2><Badge>{template.tier}</Badge></div><p className="mt-2 text-sm text-muted">{template.description}</p><p className="mt-3 text-xs text-muted">Best for {template.recommendedFor.join(", ")}</p><Button type="button" onClick={() => { setPreview(template.id); setDevice("desktop"); }} className="mt-5 w-full"><Eye size={16}/> Preview</Button></div></Card>)}</div>{preview && <div role="dialog" aria-modal="true" aria-label="Template preview" className="fixed inset-0 z-50 flex flex-col bg-slate-950/80 p-3"><div className="mx-auto flex w-full max-w-7xl items-center justify-between gap-3 rounded-t-xl bg-white p-3"><div className="flex gap-1">{([{ id: "desktop", icon: Monitor }, { id: "tablet", icon: Tablet }, { id: "mobile", icon: Smartphone }] as const).map(({ id, icon: Icon }) => <button key={id} type="button" aria-label={`${id} preview`} aria-pressed={device === id} onClick={() => setDevice(id)} className={`rounded p-2 ${device === id ? "bg-primary text-white" : "bg-surface"}`}><Icon size={17}/></button>)}</div><button type="button" aria-label="Close preview" onClick={() => setPreview(null)} className="rounded p-2 hover:bg-surface"><X/></button></div><div className="mx-auto min-h-0 w-full max-w-7xl flex-1 overflow-auto rounded-b-xl bg-slate-200 p-3"><div data-preview-device={device} className="mx-auto min-h-full overflow-hidden bg-white" style={{ width: widths[device], maxWidth: "100%" }}><PortfolioRenderer portfolio={demo} templateOverride={preview}/></div></div></div>}</>; }
