import Image from "next/image";
import type { PortfolioSection, PortfolioTemplateProps } from "../types";

type Variant = "minimal" | "developer" | "modern" | "professional" | "creative" | "student";
const names = { HERO: "Home", ABOUT: "About", EXPERIENCE: "Experience", EDUCATION: "Education", SKILLS: "Skills", PROJECTS: "Projects", SOCIAL: "Contact", RESUME: "Resume" } as const;
function hasContent(type: PortfolioSection["sectionType"], p: PortfolioTemplateProps["portfolio"]) { return type === "HERO" || (type === "ABOUT" && Boolean(p.bio)) || (type === "EXPERIENCE" && p.experiences.length > 0) || (type === "EDUCATION" && p.educations.length > 0) || (type === "SKILLS" && p.skills.length > 0) || (type === "PROJECTS" && p.projects.length > 0) || (type === "SOCIAL" && (p.socialLinks.length > 0 || Boolean(p.publicEmail))) || (type === "RESUME" && Boolean(p.resume?.available && p.resume.url)); }

export function TemplateLayout({ portfolio, sections, variant }: PortfolioTemplateProps & { variant: Variant }) {
  const ordered = sections.filter((s) => s.enabled && hasContent(s.sectionType, portfolio)).sort((a, b) => a.position - b.position);
  return <main className={`portfolio-${variant} min-h-screen overflow-x-hidden bg-[var(--portfolio-background)] text-[var(--portfolio-text)]`} style={{ fontFamily: "var(--portfolio-font-body)" }}>
    <nav aria-label="Portfolio sections" className="border-b border-current/10"><div className="mx-auto flex max-w-[var(--portfolio-content-width)] items-center justify-between gap-5 px-5 py-4"><strong style={{ fontFamily: "var(--portfolio-font-heading)" }}>{portfolio.fullName}</strong><div className="hidden flex-wrap gap-5 text-sm sm:flex">{ordered.filter((s) => !["HERO", "RESUME"].includes(s.sectionType)).map((s) => <a key={s.sectionType} href={`#portfolio-${s.sectionType.toLowerCase()}`} className="opacity-70 hover:opacity-100 focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-[var(--portfolio-primary)]">{names[s.sectionType]}</a>)}</div></div></nav>
    <div className="mx-auto max-w-[var(--portfolio-content-width)] px-5 py-8 sm:px-8">{ordered.map((section) => <TemplateSection key={section.sectionType} section={section} variant={variant} portfolio={portfolio} />)}</div>
  </main>;
}

function TemplateSection({ section, portfolio, variant }: { section: PortfolioSection; portfolio: PortfolioTemplateProps["portfolio"]; variant: Variant }) {
  const type = section.sectionType; const card = "rounded-[var(--portfolio-radius)] border border-current/10 bg-[var(--portfolio-surface)]";
  const wrap = (title: string, children: React.ReactNode) => <section id={`portfolio-${type.toLowerCase()}`} aria-labelledby={`${type.toLowerCase()}-heading`} className="scroll-mt-20 py-[calc(var(--portfolio-section-gap)/2)]"><h2 id={`${type.toLowerCase()}-heading`} className={`${variant === "creative" ? "text-4xl sm:text-5xl" : "text-2xl sm:text-3xl"} mb-6 font-bold`} style={{ fontFamily: "var(--portfolio-font-heading)" }}>{title}</h2>{children}</section>;
  if (type === "HERO") return <header className={`py-[var(--portfolio-section-gap)] ${variant === "modern" ? `${card} my-6 px-6 text-center sm:px-12` : variant === "creative" ? "grid items-end gap-8 sm:grid-cols-[1fr_1.4fr]" : variant === "developer" ? "border-l-4 pl-6" : "flex flex-col gap-7 sm:flex-row sm:items-center"}`} style={variant === "developer" ? { borderColor: "var(--portfolio-primary)" } : undefined}>{portfolio.profileImageUrl && <Image src={portfolio.profileImageUrl} alt={`${portfolio.fullName} profile photo`} width={variant === "creative" ? 420 : 144} height={variant === "creative" ? 520 : 144} sizes="(max-width: 640px) 100vw, 420px" className={`${variant === "creative" ? "aspect-[4/5] w-full" : "size-28 sm:size-36"} rounded-[var(--portfolio-radius)] object-cover`} />}<div><p className="mb-3 text-sm font-bold uppercase tracking-[.18em] text-[var(--portfolio-primary)]">{variant === "developer" ? "Portfolio / developer" : portfolio.location}</p><h1 className={`${variant === "creative" ? "text-6xl sm:text-8xl" : "text-4xl sm:text-6xl"} font-bold leading-[.95] tracking-tight`} style={{ fontFamily: "var(--portfolio-font-heading)" }}>{portfolio.fullName}</h1>{portfolio.headline && <p className="mt-5 max-w-2xl text-lg text-[var(--portfolio-muted)] sm:text-xl">{portfolio.headline}</p>}</div></header>;
  if (type === "ABOUT") return wrap("About", <p className={`max-w-3xl whitespace-pre-wrap leading-8 text-[var(--portfolio-muted)] ${variant === "minimal" ? "text-xl" : "text-lg"}`}>{portfolio.bio}</p>);
  if (type === "EXPERIENCE") return wrap("Experience", <div className={variant === "modern" ? "grid gap-4 md:grid-cols-2" : "space-y-5"}>{portfolio.experiences.map((item) => <article key={item.id} className={variant === "professional" ? "border-l-2 pl-5" : variant === "modern" ? `${card} p-5` : ""} style={variant === "professional" ? { borderColor: "var(--portfolio-primary)" } : undefined}><h3 className="font-bold">{item.position}</h3><p className="text-[var(--portfolio-primary)]">{item.company}</p>{item.description && <p className="mt-2 whitespace-pre-wrap text-[var(--portfolio-muted)]">{item.description}</p>}</article>)}</div>);
  if (type === "EDUCATION") return wrap("Education", <div className={variant === "student" ? "grid gap-4 sm:grid-cols-2" : "space-y-4"}>{portfolio.educations.map((item) => <article key={item.id} className={variant === "student" ? `${card} p-5` : ""}><h3 className="font-bold">{item.school}</h3>{item.degree && <p className="text-[var(--portfolio-muted)]">{item.degree}{item.major ? ` · ${item.major}` : ""}</p>}</article>)}</div>);
  if (type === "SKILLS") return wrap("Skills", <div className={variant === "student" ? "grid grid-cols-2 gap-3 sm:grid-cols-3" : "flex flex-wrap gap-2"}>{portfolio.skills.map((skill) => <span key={skill.id} className={`${card} px-3 py-2 text-sm ${variant === "developer" ? "font-mono" : ""}`}>{variant === "developer" ? `<${skill.name}>` : skill.name}</span>)}</div>);
  if (type === "PROJECTS") return wrap("Selected work", <div className={variant === "minimal" || section.layout === "list" ? "space-y-5" : "grid gap-5 sm:grid-cols-2"}>{portfolio.projects.slice().sort((a, b) => Number(b.featured) - Number(a.featured)).map((project, index) => <article key={project.id} className={`${card} overflow-hidden ${variant === "creative" && index === 0 ? "sm:col-span-2" : ""}`}>{project.thumbnailUrl && <Image src={project.thumbnailUrl} alt={`${project.title} project preview`} width={1200} height={675} sizes="(max-width: 768px) 100vw, 50vw" className="aspect-video w-full object-cover" />}<div className="p-5"><h3 className="text-lg font-bold">{project.title}</h3>{project.shortDescription && <p className="mt-2 text-[var(--portfolio-muted)]">{project.shortDescription}</p>}<div className="mt-4 flex flex-wrap gap-2">{project.technologies?.map((technology) => <span key={technology} className="text-xs text-[var(--portfolio-primary)]">{technology}</span>)}</div>{(project.demoUrl || project.githubUrl) && <div className="mt-4 flex gap-4 text-sm font-semibold">{project.demoUrl && <a href={project.demoUrl} target="_blank" rel="noreferrer">Live project</a>}{project.githubUrl && <a href={project.githubUrl} target="_blank" rel="noreferrer">Source code</a>}</div>}</div></article>)}</div>);
  if (type === "SOCIAL") return wrap("Contact", <div className="flex flex-wrap gap-5">{portfolio.publicEmail && <a className="text-[var(--portfolio-primary)]" href={`mailto:${portfolio.publicEmail}`}>{portfolio.publicEmail}</a>}{portfolio.socialLinks.map((item) => <a key={item.id} href={item.url} className="text-[var(--portfolio-primary)]" target="_blank" rel="noreferrer">{item.platform}</a>)}</div>);
  if (type === "RESUME") return <section id="portfolio-resume" className="py-[calc(var(--portfolio-section-gap)/2)]"><a href={portfolio.resume?.url} className="inline-flex rounded-[var(--portfolio-radius)] bg-[var(--portfolio-primary)] px-5 py-3 font-bold text-white">Download resume</a></section>;
  return null;
}
