import Image from "next/image";
import type { PortfolioTemplateProps } from "../types";

type Variant = "minimal" | "developer" | "modern" | "professional" | "creative" | "student";
const fallbackOrder = ["HERO", "ABOUT", "EXPERIENCE", "PROJECTS", "SKILLS", "EDUCATION", "CONTACT"];
const radius = { none: "rounded-none", small: "rounded-md", medium: "rounded-xl", large: "rounded-3xl" };

export function TemplateLayout({ portfolio, theme, sections, variant }: PortfolioTemplateProps & { variant: Variant }) {
  const ordered = (sections.length ? sections : fallbackOrder.map((sectionType, index) => ({ sectionType, position: index + 1, enabled: true }))).filter((section) => section.enabled).sort((a, b) => a.position - b.position);
  const dark = theme.mode === "dark" || variant === "developer";
  const style = { background: dark ? "#0b1220" : theme.backgroundColor, color: dark ? "#f8fafc" : theme.textColor, fontFamily: theme.fontFamily };
  const width = { narrow: "max-w-2xl", medium: "max-w-4xl", wide: "max-w-6xl" }[theme.contentWidth];
  return <main style={style} className="min-h-screen overflow-x-hidden"><div className={`mx-auto ${width} px-5 py-10 sm:px-8 sm:py-14`}>{ordered.map((section) => <TemplateSection key={section.sectionType} type={section.sectionType} variant={variant} portfolio={portfolio} theme={theme} cardRadius={radius[theme.radius]} />)}</div></main>;
}

function TemplateSection({ type, portfolio, theme, variant, cardRadius }: { type: string; portfolio: PortfolioTemplateProps["portfolio"]; theme: PortfolioTemplateProps["theme"]; variant: Variant; cardRadius: string }) {
  const heading = (title: string) => <h2 className={variant === "creative" ? "mb-7 text-4xl font-bold" : "mb-5 text-2xl font-bold"}>{title}</h2>;
  const wrap = (title: string, content: React.ReactNode) => <section aria-labelledby={`${type.toLowerCase()}-heading`} className="mt-12 border-t border-current/15 pt-7"><div id={`${type.toLowerCase()}-heading`}>{heading(title)}</div>{content}</section>;
  if (type === "HERO") return <header className={variant === "modern" || variant === "creative" ? "py-10 text-center" : "flex flex-col gap-6 py-7 sm:flex-row sm:items-center"}>{portfolio.profileImageUrl && <Image src={portfolio.profileImageUrl} alt={`${portfolio.fullName} profile photo`} width={variant === "creative" ? 180 : 104} height={variant === "creative" ? 180 : 104} sizes="(max-width: 640px) 104px, 180px" className={`${cardRadius} mx-auto aspect-square object-cover sm:mx-0`} />}<div className={variant === "modern" || variant === "creative" ? "mx-auto" : ""}>{portfolio.location && <p style={{ color: theme.primaryColor }} className="font-semibold">{portfolio.location}</p>}<h1 className={`${variant === "creative" ? "text-6xl" : "text-4xl sm:text-5xl"} mt-2 font-bold tracking-tight`}>{variant === "developer" ? "// " : ""}{portfolio.fullName}</h1>{portfolio.headline && <p className="mt-4 text-lg opacity-70 sm:text-xl">{portfolio.headline}</p>}{portfolio.resume?.available && portfolio.resume.url && <a href={portfolio.resume.url} className={`mt-6 inline-block ${cardRadius} px-4 py-2 text-sm font-semibold text-white`} style={{ background: theme.primaryColor }}>Download Resume</a>}</div></header>;
  if (type === "ABOUT" && portfolio.bio) return wrap("About", <p className="max-w-3xl whitespace-pre-wrap text-lg leading-8 opacity-75">{portfolio.bio}</p>);
  if (type === "EXPERIENCE" && portfolio.experiences.length) return wrap("Experience", <div className="space-y-5">{portfolio.experiences.map((item) => <article key={item.id} className={variant === "professional" ? "border-l-4 pl-5" : ""} style={variant === "professional" ? { borderColor: theme.primaryColor } : undefined}><h3 className="font-semibold">{item.position} · {item.company}</h3>{item.description && <p className="mt-2 whitespace-pre-wrap opacity-70">{item.description}</p>}</article>)}</div>);
  if (type === "PROJECTS" && portfolio.projects.length) return wrap("Projects", <div className={variant === "minimal" || theme.projectLayout === "list" ? "space-y-5" : variant === "creative" ? "grid gap-6 md:grid-cols-2" : "grid gap-4 sm:grid-cols-2"}>{portfolio.projects.slice().sort((a, b) => Number(b.featured) - Number(a.featured)).map((project) => <article key={project.id} className={`${cardRadius} overflow-hidden border border-current/15 ${variant === "creative" ? "first:md:col-span-2" : ""}`}>{project.thumbnailUrl && <Image src={project.thumbnailUrl} alt={`${project.title} project`} width={960} height={540} sizes="(max-width: 768px) 100vw, 50vw" className="aspect-video w-full object-cover" />}<div className="p-5"><h3 className="text-lg font-bold">{project.title}</h3>{project.shortDescription && <p className="mt-2 opacity-70">{project.shortDescription}</p>}{project.technologies?.length ? <div className="mt-4 flex flex-wrap gap-2">{project.technologies.map((technology) => <span key={technology} className={`${cardRadius} border border-current/15 px-2 py-1 text-xs`}>{technology}</span>)}</div> : null}</div></article>)}</div>);
  if (type === "SKILLS" && portfolio.skills.length) return wrap("Skills", <div className="flex flex-wrap gap-2">{portfolio.skills.map((item) => <span key={item.id} className={`${cardRadius} border border-current/20 px-3 py-1 text-sm`}>{item.name}</span>)}</div>);
  if (type === "EDUCATION" && portfolio.educations.length) return wrap("Education", <div className="space-y-3">{portfolio.educations.map((item) => <article key={item.id}><h3 className="font-semibold">{item.school}</h3>{item.degree && <p className="opacity-70">{item.degree}{item.major ? ` · ${item.major}` : ""}</p>}</article>)}</div>);
  if (type === "CONTACT" && (portfolio.publicEmail || portfolio.socialLinks.length)) return wrap("Contact", <div className="flex flex-wrap gap-4">{portfolio.publicEmail && <a href={`mailto:${portfolio.publicEmail}`} style={{ color: theme.primaryColor }}>{portfolio.publicEmail}</a>}{portfolio.socialLinks.map((item) => <a key={item.id} href={item.url} style={{ color: theme.primaryColor }} target="_blank" rel="noreferrer">{item.platform}</a>)}</div>);
  return null;
}
