package com.portfolio.features.resume.parser;
import com.portfolio.features.resume.dto.ResumePreviewResponse;
import java.util.*;
import java.util.regex.*;
import org.springframework.stereotype.Component;

@Component
public class RuleBasedResumeParser implements ResumeParser {
  private static final Pattern EMAIL = Pattern.compile("\\b[A-Z0-9._%+-]+@[A-Z0-9.-]+\\.[A-Z]{2,}\\b", Pattern.CASE_INSENSITIVE);
  private static final Pattern PHONE = Pattern.compile("(?<!\\w)(?:\\+?\\d[\\d .()-]{6,}\\d)(?!\\w)");
  private static final Pattern URL = Pattern.compile("https?://[^\\s]+|(?:www\\.)?github\\.com/[^\\s]+|(?:www\\.)?linkedin\\.com/in/[^\\s]+", Pattern.CASE_INSENSITIVE);
  private static final Pattern DATE = Pattern.compile("(?i)(?:[A-Z][a-z]+\\s+)?(?:\\d{1,2}/)?\\d{4}\\s*[-–—]\\s*(?:present|current|(?:[A-Z][a-z]+\\s+)?(?:\\d{1,2}/)?\\d{4})");
  private static final Map<String, Set<String>> HEADINGS = Map.of("experience", Set.of("EXPERIENCE","WORK EXPERIENCE","EMPLOYMENT","PROFESSIONAL EXPERIENCE","WORK HISTORY"), "education", Set.of("EDUCATION","ACADEMIC BACKGROUND","ACADEMIC HISTORY"), "skills", Set.of("SKILLS","TECHNICAL SKILLS","TECHNOLOGIES","TECH STACK"), "projects", Set.of("PROJECTS","PERSONAL PROJECTS","SELECTED PROJECTS","ACADEMIC PROJECTS"));

  @Override public ResumePreviewResponse parse(String text) {
    List<String> lines = text.lines().map(String::trim).toList(); Map<String, List<String>> sections = sections(lines); List<String> warnings = new ArrayList<>();
    List<ResumePreviewResponse.Experience> experience = experiences(sections.get("experience")); if (experience.isEmpty()) warnings.add("No experience section was detected.");
    List<ResumePreviewResponse.Education> education = education(sections.get("education")); if (education.isEmpty()) warnings.add("No education section was detected.");
    List<ResumePreviewResponse.Skill> skills = skills(sections.get("skills")); if (skills.isEmpty()) warnings.add("No skills section was detected.");
    List<ResumePreviewResponse.Project> projects = projects(sections.get("projects")); if (projects.isEmpty()) warnings.add("No projects section was detected.");
    if (experience.stream().anyMatch(item -> item.startDate() == null)) warnings.add("Some experience dates could not be parsed.");
    return new ResumePreviewResponse(profile(lines), experience, education, skills, projects, warnings);
  }
  private Map<String,List<String>> sections(List<String> lines) { Map<String,List<String>> result = new HashMap<>(); String active = null; for (String line : lines) { String heading = normalize(line); String found = HEADINGS.entrySet().stream().filter(entry -> entry.getValue().contains(heading)).map(Map.Entry::getKey).findFirst().orElse(null); if (found != null) { active = found; result.putIfAbsent(active, new ArrayList<>()); } else if (active != null) result.get(active).add(line); } return result; }
  private ResumePreviewResponse.Profile profile(List<String> lines) { String all = String.join("\n", lines); String email = match(EMAIL, all), phone = match(PHONE, all), github = url(all,"github.com"), linkedin = url(all,"linkedin.com/in"), website = URL.matcher(all).results().map(MatchResult::group).filter(value -> !value.toLowerCase().contains("github.com") && !value.toLowerCase().contains("linkedin.com")).findFirst().orElse(null); String name = lines.stream().limit(6).filter(line -> line.length() > 2 && line.length() < 60 && !line.contains("@") && !URL.matcher(line).find() && !PHONE.matcher(line).find() && !isHeading(line) && !DATE.matcher(line).find()).findFirst().orElse(null); String headline = name == null ? null : lines.stream().limit(8).filter(line -> !line.equals(name) && line.length() > 3 && line.length() < 80 && !line.contains("@") && !isHeading(line) && !URL.matcher(line).find()).findFirst().orElse(null); return new ResumePreviewResponse.Profile(name, headline, email, phone, null, website, linkedin, github); }
  private List<ResumePreviewResponse.Skill> skills(List<String> lines) { if (lines == null) return List.of(); Map<String,String> unique = new LinkedHashMap<>(); for (String line : lines) for (String value : line.split("[,;|•]")) { String skill = value.replaceAll("^[•\\-\\s]+", "").trim(); if (skill.length() > 1 && skill.length() < 60) unique.putIfAbsent(skill.toLowerCase(Locale.ROOT), skill); } return unique.values().stream().map(value -> new ResumePreviewResponse.Skill(value,null)).toList(); }
  private List<ResumePreviewResponse.Experience> experiences(List<String> lines) { if (lines == null) return List.of(); return blocks(lines).stream().map(block -> { List<String> values = nonBlank(block); String date = values.stream().filter(value -> DATE.matcher(value).find()).findFirst().orElse(null); List<String> main = values.stream().filter(value -> !value.equals(date) && !value.startsWith("•")).toList(); String raw = String.join("\n", values); String[] range = date == null ? new String[]{null,null} : date.split("\\s*[-–—]\\s*",2); return new ResumePreviewResponse.Experience(main.size()>1?main.get(1):null, main.isEmpty()?null:main.getFirst(), null, range[0], range.length>1 && !range[1].equalsIgnoreCase("present") ? range[1] : null, date != null && date.toLowerCase().contains("present"), values.stream().filter(value -> value.startsWith("•")).map(value -> value.substring(1).trim()).reduce((a,b)->a+"\n"+b).orElse(null), raw); }).filter(item -> item.position()!=null).toList(); }
  private List<ResumePreviewResponse.Education> education(List<String> lines) { if (lines == null) return List.of(); return blocks(lines).stream().map(block -> { List<String> values=nonBlank(block); String raw=String.join("\n",values); String school=values.stream().filter(value -> value.matches("(?i).*\\b(university|college|institute|school)\\b.*")).findFirst().orElse(null); String degree=values.stream().filter(value -> value.matches("(?i).*\\b(bachelor|master|phd|bsc|bs|ba|msc|mba)\\b.*")).findFirst().orElse(null); return new ResumePreviewResponse.Education(school,degree,null,null,null,null,raw); }).filter(item -> item.school()!=null || item.degree()!=null).toList(); }
  private List<ResumePreviewResponse.Project> projects(List<String> lines) { if (lines == null) return List.of(); return blocks(lines).stream().map(block -> { List<String> values=nonBlank(block); String raw=String.join("\n",values); String github=url(raw,"github.com"), demo=URL.matcher(raw).results().map(MatchResult::group).filter(value -> !value.toLowerCase().contains("github.com")).findFirst().orElse(null); return new ResumePreviewResponse.Project(values.isEmpty()?null:values.getFirst(), values.size()>1?String.join(" ",values.subList(1,values.size())):null,github,demo,List.of(),raw); }).filter(item -> item.title()!=null).toList(); }
  private List<List<String>> blocks(List<String> lines) { if (lines == null) return List.of(); List<List<String>> result=new ArrayList<>(); List<String> current=new ArrayList<>(); for(String line:lines){if(line.isBlank()){if(!current.isEmpty()){result.add(current);current=new ArrayList<>();}}else current.add(line);} if(!current.isEmpty())result.add(current); return result; }
  private List<String> nonBlank(List<String> values){return values.stream().filter(value->!value.isBlank()).toList();} private String match(Pattern pattern,String text){Matcher matcher=pattern.matcher(text);return matcher.find()?matcher.group():null;} private String url(String text,String contains){return URL.matcher(text).results().map(MatchResult::group).filter(value->value.toLowerCase().contains(contains)).findFirst().orElse(null);} private String normalize(String value){return value.trim().toUpperCase(Locale.ROOT).replaceAll(":$","");} private boolean isHeading(String value){return HEADINGS.values().stream().anyMatch(set->set.contains(normalize(value)));}
}
